import Head from "next/head";

import { About } from "../widgets/about";
import { Advantages } from "../widgets/advantages";
import { ContactUs } from "../widgets/contact-us";
import { Hero } from "../widgets/hero";
import { Layout } from "../widgets/layout/Layout";
import { OurTeam } from "../widgets/our-team";
import { Roadmap } from "../widgets/roadmap";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Hero />
        <About />
        <Advantages />
        <Roadmap />
        <OurTeam />
        <ContactUs />
      </Layout>
    </>
  );
}
